services:


######################### api #########################
 
  # api:
  #   container_name: api
  #   restart: always
  #   build:
  #     context: ./app
  #     dockerfile: dockerfile
  #   #volumes:  
  #     #- ${PATH_LOG}:/system_log
  #     #- ${PATH_DATA}:/system_data
  #   ports:
  #     - 8010:8010
  #   environment:

  #   networks:
  #     - my_network


######################### Redis #########################
#   redis:
#     container_name: redis
#     image: redis:latest
#     restart: always
#     ports:
#       - 50030:6379
#     command: redis-server --maxmemory 50GB --maxmemory-policy allkeys-lru --save "" --appendonly no --requirepass senha123teste #--requirepass sua_senha_aqui
#     networks:
#       - my_network
    
#   redis_insight:
#     image: redislabs/redisinsight:latest
#     container_name: redis_insight
#     restart: always
#     ports:
#       - 50031:5540
# #    volumes:
# #      - ${PATH_REDIS_INSIGHT}:/db
#     networks:
#       - my_network

######################### Mongo #########################

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  grafana:
    image: grafana/grafana-enterprise
    #container_name: grafana
    restart: unless-stopped
    user: '0'
    ports:
      - 3000:3000

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: automate
      # GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      #TZ: 'America/Sao_Paulo'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./configs/grafana_config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./configs/grafana_config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./configs/grafana_config/dashboards/my_dashboard.json:/var/lib/grafana/dashboards/my_dashboard.json




