apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    url: 10.247.141.99:8900
    user: root
    database: monitoring
    secureJsonData:
      password: automate123.
    jsonData:
      sslmode: disable
      postgresVersion: 1200